version: "3.1"
name: AreyouAlive

services:
  areyoualive:
    container_name: areyoualive
    build:
      context: .
    image: fca/areyoualive
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always
